import { mergeUnique } from "../utils/updateUtil";
import { dataMap } from "./AutoGenerateData"

// 游戏内可自定义头像
export const _AvatarList = [
    {
        "name": "“符号”",
        "img": "https://media.prts.wiki/thumb/d/d5/Avatar_def_01.png/120px-Avatar_def_01.png"
    },
    {
        "name": "“档案室”",
        "img": "https://media.prts.wiki/thumb/5/59/Avatar_def_02.png/120px-Avatar_def_02.png"
    },
    {
        "name": "“从此出”",
        "img": "https://media.prts.wiki/thumb/3/34/Avatar_def_03.png/120px-Avatar_def_03.png"
    },
    {
        "name": "“注意大黑”",
        "img": "https://media.prts.wiki/thumb/f/f4/Avatar_def_04.png/120px-Avatar_def_04.png"
    },
    {
        "name": "“补充简历”",
        "img": "https://media.prts.wiki/thumb/b/b6/Avatar_def_05.png/120px-Avatar_def_05.png"
    },
    {
        "name": "“3min”",
        "img": "https://media.prts.wiki/thumb/f/fe/Avatar_def_06.png/120px-Avatar_def_06.png"
    },
    {
        "name": "“Good Game”",
        "img": "https://media.prts.wiki/thumb/e/e9/Avatar_def_07.png/120px-Avatar_def_07.png"
    },
    {
        "name": "“PRTS”",
        "img": "https://media.prts.wiki/thumb/7/7d/Avatar_def_08.png/120px-Avatar_def_08.png"
    },
    {
        "name": "“希望消逝”",
        "img": "https://media.prts.wiki/thumb/1/16/Avatar_def_09.png/120px-Avatar_def_09.png"
    },
    {
        "name": "“请勿模仿”",
        "img": "https://media.prts.wiki/thumb/5/5a/Avatar_def_10.png/120px-Avatar_def_10.png"
    },
    {
        "name": "“晚餐”",
        "img": "https://media.prts.wiki/thumb/6/67/Avatar_def_11.png/120px-Avatar_def_11.png"
    },
    {
        "name": "“禁止加班”",
        "img": "https://media.prts.wiki/thumb/d/d3/Avatar_def_12.png/120px-Avatar_def_12.png"
    },
    {
        "name": "“球体”",
        "img": "https://media.prts.wiki/thumb/2/24/Avatar_def_13.png/120px-Avatar_def_13.png"
    },
    {
        "name": "“沙漠金币”",
        "img": "https://media.prts.wiki/thumb/4/4f/Avatar_def_14.png/120px-Avatar_def_14.png"
    },
    {
        "name": "“WARNING”",
        "img": "https://media.prts.wiki/thumb/2/20/Avatar_def_15.png/120px-Avatar_def_15.png"
    },
    {
        "name": "“黎明前奏”",
        "img": "https://media.prts.wiki/thumb/7/75/Avatar_special_01.png/120px-Avatar_special_01.png"
    },
    {
        "name": "“沙滩急救”",
        "img": "https://media.prts.wiki/thumb/f/f0/Avatar_special_02.png/120px-Avatar_special_02.png"
    },
    {
        "name": "“滨水守卫”",
        "img": "https://media.prts.wiki/thumb/d/d7/Avatar_special_03.png/120px-Avatar_special_03.png"
    },
    {
        "name": "“2022余韵切片”",
        "img": "https://media.prts.wiki/thumb/6/66/Avatar_special_04.png/120px-Avatar_special_04.png"
    },
    {
        "name": "“导演的认可”",
        "img": "https://media.prts.wiki/thumb/7/7a/Avatar_special_05.png/120px-Avatar_special_05.png"
    },
    {
        "name": "“徘徊歧路”",
        "img": "https://media.prts.wiki/thumb/9/92/Avatar_special_06.png/120px-Avatar_special_06.png"
    },
    {
        "name": "“寻火之叶”",
        "img": "https://media.prts.wiki/thumb/d/de/Avatar_special_07.png/120px-Avatar_special_07.png"
    },
    {
        "name": "“2023余韵切片”",
        "img": "https://media.prts.wiki/thumb/a/a4/Avatar_special_08.png/120px-Avatar_special_08.png"
    },
    {
        "name": "“回眸一笑”",
        "img": "https://media.prts.wiki/thumb/0/0e/Avatar_special_09.png/120px-Avatar_special_09.png"
    },
    {
        "name": "“记事拾遗”",
        "img": "https://media.prts.wiki/thumb/5/59/Avatar_special_10.png/120px-Avatar_special_10.png"
    },
    {
        "name": "“天外宫阙”",
        "img": "https://media.prts.wiki/thumb/e/e8/Avatar_special_11.png/120px-Avatar_special_11.png"
    },
    {
        "name": "“目的地”",
        "img": "https://media.prts.wiki/thumb/4/49/Avatar_special_12.png/120px-Avatar_special_12.png"
    },
    {
        "name": "“白兔子”",
        "img": "https://media.prts.wiki/thumb/4/43/Avatar_special_13.png/120px-Avatar_special_13.png"
    },
    {
        "name": "“口袋舰船”",
        "img": "https://media.prts.wiki/thumb/8/85/Avatar_special_14.png/120px-Avatar_special_14.png"
    },
    {
        "name": "“防守”",
        "img": "https://media.prts.wiki/thumb/b/b2/Avatar_special_15.png/120px-Avatar_special_15.png"
    },
    {
        "name": "“进攻”",
        "img": "https://media.prts.wiki/thumb/1/1c/Avatar_special_16.png/120px-Avatar_special_16.png"
    },
    {
        "name": "“2024余韵切片”",
        "img": "https://media.prts.wiki/thumb/a/a6/Avatar_special_17.png/120px-Avatar_special_17.png"
    },
    {
        "name": "“祈望星光”",
        "img": "https://media.prts.wiki/thumb/7/7c/Avatar_special_18.png/120px-Avatar_special_18.png"
    },
    {
        "name": "“很酷，不聊天”",
        "img": "https://media.prts.wiki/thumb/a/a8/Avatar_special_19.png/120px-Avatar_special_19.png"
    },
    {
        "name": "“蝴蝶结交流会”",
        "img": "https://media.prts.wiki/thumb/2/2d/Avatar_special_20.png/120px-Avatar_special_20.png"
    },
    {
        "name": "“侦探组合”",
        "img": "https://media.prts.wiki/thumb/d/df/Avatar_special_21.png/120px-Avatar_special_21.png"
    },
    {
        "name": "“尤里卡的梦”",
        "img": "https://media.prts.wiki/thumb/3/3f/Avatar_special_22.png/120px-Avatar_special_22.png"
    },
    {
        "name": "“Wink——”",
        "img": "https://media.prts.wiki/thumb/e/e2/Avatar_special_23.png/120px-Avatar_special_23.png"
    },
    {
        "name": "“骷髅与少女心”",
        "img": "https://media.prts.wiki/thumb/a/a1/Avatar_special_24.png/120px-Avatar_special_24.png"
    },
    {
        "name": "“云上的天使”",
        "img": "https://media.prts.wiki/thumb/e/e2/Avatar_special_25.png/120px-Avatar_special_25.png"
    },
    {
        "name": "“沉默的人与蛋”",
        "img": "https://media.prts.wiki/thumb/b/bf/Avatar_special_26.png/120px-Avatar_special_26.png"
    },
    {
        "name": "“浇灌磐蟹”",
        "img": "https://media.prts.wiki/thumb/d/d9/Avatar_special_27.png/120px-Avatar_special_27.png"
    },
    {
        "name": "“惊骇盐风”",
        "img": "https://media.prts.wiki/thumb/b/b5/Avatar_special_28.png/120px-Avatar_special_28.png"
    },
    {
        "name": "“点墨奇思”",
        "img": "https://media.prts.wiki/thumb/8/89/Avatar_special_29.png/120px-Avatar_special_29.png"
    },
    {
        "name": "“快赶走啦！”",
        "img": "https://media.prts.wiki/thumb/4/4d/Avatar_special_30.png/120px-Avatar_special_30.png"
    },
    {
        "name": "“蓄能”",
        "img": "https://media.prts.wiki/thumb/7/76/Avatar_special_31.png/120px-Avatar_special_31.png"
    },
    {
        "name": "“这照片是你吗？”",
        "img": "https://media.prts.wiki/thumb/d/db/Avatar_special_32.png/120px-Avatar_special_32.png"
    },
    {
        "name": "“咔！”",
        "img": "https://media.prts.wiki/thumb/2/27/Avatar_special_33.png/120px-Avatar_special_33.png"
    },
    {
        "name": "“重岳故事”",
        "img": "https://media.prts.wiki/thumb/a/ac/Avatar_special_34.png/120px-Avatar_special_34.png"
    },
    {
        "name": "“兔兔小夜曲”",
        "img": "https://media.prts.wiki/thumb/8/8c/Avatar_special_35.png/120px-Avatar_special_35.png"
    },
    {
        "name": "“兔兔店员”",
        "img": "https://media.prts.wiki/thumb/a/a7/Avatar_special_36.png/120px-Avatar_special_36.png"
    },
    {
        "name": "“火蓝之心”",
        "img": "https://media.prts.wiki/thumb/f/fa/Avatar_activity_OF.png/120px-Avatar_activity_OF.png"
    },
    {
        "name": "“骑兵与猎人”",
        "img": "https://media.prts.wiki/thumb/0/03/Avatar_activity_GK.png/120px-Avatar_activity_GK.png"
    },
    {
        "name": "“战地秘闻”",
        "img": "https://media.prts.wiki/thumb/9/93/Avatar_activity_OI.png/120px-Avatar_activity_OI.png"
    },
    {
        "name": "“喧闹法则”",
        "img": "https://media.prts.wiki/thumb/2/2f/Avatar_activity_CB.png/120px-Avatar_activity_CB.png"
    },
    {
        "name": "“洪炉示岁”",
        "img": "https://media.prts.wiki/thumb/4/43/Avatar_activity_AF.png/120px-Avatar_activity_AF.png"
    },
    {
        "name": "“猩红剧团”",
        "img": "https://media.prts.wiki/thumb/a/a5/Avatar_activity_RL1_1.png/120px-Avatar_activity_RL1_1.png"
    },
    {
        "name": "“傀影常在”",
        "img": "https://media.prts.wiki/thumb/0/04/Avatar_activity_RL1_2.png/120px-Avatar_activity_RL1_2.png"
    },
    {
        "name": "“午间逸话”",
        "img": "https://media.prts.wiki/thumb/7/74/Avatar_activity_SA.png/120px-Avatar_activity_SA.png"
    },
    {
        "name": "“碎片大厦”",
        "img": "https://media.prts.wiki/thumb/8/8f/Avatar_activity_EP10_1.png/120px-Avatar_activity_EP10_1.png"
    },
    {
        "name": "“日冕”",
        "img": "https://media.prts.wiki/thumb/b/b2/Avatar_activity_EP10_2.png/120px-Avatar_activity_EP10_2.png"
    },
    {
        "name": "“乌萨斯的孩子们”",
        "img": "https://media.prts.wiki/thumb/4/47/Avatar_activity_SV.png/120px-Avatar_activity_SV.png"
    },
    {
        "name": "“生于黑夜”",
        "img": "https://media.prts.wiki/thumb/4/45/Avatar_activity_BN.png/120px-Avatar_activity_BN.png"
    },
    {
        "name": "“沃伦姆德的薄暮”",
        "img": "https://media.prts.wiki/thumb/3/33/Avatar_activity_TW.png/120px-Avatar_activity_TW.png"
    },
    {
        "name": "“踏寻往昔之风”",
        "img": "https://media.prts.wiki/thumb/8/88/Avatar_activity_FA.png/120px-Avatar_activity_FA.png"
    },
    {
        "name": "“密林悍将归来”",
        "img": "https://media.prts.wiki/thumb/1/19/Avatar_activity_RI.png/120px-Avatar_activity_RI.png"
    },
    {
        "name": "“此地之外”",
        "img": "https://media.prts.wiki/thumb/9/9c/Avatar_activity_BH.png/120px-Avatar_activity_BH.png"
    },
    {
        "name": "“诸王之息”",
        "img": "https://media.prts.wiki/thumb/c/c7/Avatar_activity_EP11.png/120px-Avatar_activity_EP11.png"
    },
    {
        "name": "“玛莉娅·临光”",
        "img": "https://media.prts.wiki/thumb/0/04/Avatar_activity_MN.png/120px-Avatar_activity_MN.png"
    },
    {
        "name": "“深蓝印记”",
        "img": "https://media.prts.wiki/thumb/f/f3/Avatar_activity_RL2_1.png/120px-Avatar_activity_RL2_1.png"
    },
    {
        "name": "“循环”",
        "img": "https://media.prts.wiki/thumb/9/95/Avatar_activity_RL2_2.png/120px-Avatar_activity_RL2_2.png"
    },
    {
        "name": "“灯火序曲”",
        "img": "https://media.prts.wiki/thumb/0/0f/Avatar_activity_PL.png/120px-Avatar_activity_PL.png"
    },
    {
        "name": "“孤岛风云”",
        "img": "https://media.prts.wiki/thumb/c/c2/Avatar_activity_MB.png/120px-Avatar_activity_MB.png"
    },
    {
        "name": "“画中人”",
        "img": "https://media.prts.wiki/thumb/d/d3/Avatar_activity_WR.png/120px-Avatar_activity_WR.png"
    },
    {
        "name": "“如我所见”",
        "img": "https://media.prts.wiki/thumb/c/ce/Avatar_activity_VI.png/120px-Avatar_activity_VI.png"
    },
    {
        "name": "“苍暮印象”",
        "img": "https://media.prts.wiki/thumb/0/0e/Avatar_activity_HLL.png/120px-Avatar_activity_HLL.png"
    },
    {
        "name": "“影之缚”",
        "img": "https://media.prts.wiki/thumb/b/b5/Avatar_activity_EP12.png/120px-Avatar_activity_EP12.png"
    },
    {
        "name": "“遗尘漫步”",
        "img": "https://media.prts.wiki/thumb/3/38/Avatar_activity_WD.png/120px-Avatar_activity_WD.png"
    },
    {
        "name": "“红松林”",
        "img": "https://media.prts.wiki/thumb/1/12/Avatar_activity_PS.png/120px-Avatar_activity_PS.png"
    },
    {
        "name": "“覆潮之下”",
        "img": "https://media.prts.wiki/thumb/8/80/Avatar_activity_UT.png/120px-Avatar_activity_UT.png"
    },
    {
        "name": "“安玛的慈悲”",
        "img": "https://media.prts.wiki/thumb/e/ec/Avatar_activity_RL3_1.png/120px-Avatar_activity_RL3_1.png"
    },
    {
        "name": "“终古”",
        "img": "https://media.prts.wiki/thumb/9/96/Avatar_activity_RL3_2.png/120px-Avatar_activity_RL3_2.png"
    },
    {
        "name": "“多索雷斯假日”",
        "img": "https://media.prts.wiki/thumb/a/ac/Avatar_activity_DH.png/120px-Avatar_activity_DH.png"
    },
    {
        "name": "“阴云火花”",
        "img": "https://media.prts.wiki/thumb/f/fe/Avatar_activity_TB.png/120px-Avatar_activity_TB.png"
    },
    {
        "name": "“长夜临光”",
        "img": "https://media.prts.wiki/thumb/9/9c/Avatar_activity_NL.png/120px-Avatar_activity_NL.png"
    },
    {
        "name": "“巨骸湍流”",
        "img": "https://media.prts.wiki/thumb/2/2b/Avatar_activity_EP13.png/120px-Avatar_activity_EP13.png"
    },
    {
        "name": "“风雪过境”",
        "img": "https://media.prts.wiki/thumb/a/a7/Avatar_activity_BI.png/120px-Avatar_activity_BI.png"
    },
    {
        "name": "“未尽篇章”",
        "img": "https://media.prts.wiki/thumb/b/b1/Avatar_activity_TC.png/120px-Avatar_activity_TC.png"
    },
    {
        "name": "“将进酒”",
        "img": "https://media.prts.wiki/thumb/2/29/Avatar_activity_IW.png/120px-Avatar_activity_IW.png"
    },
    {
        "name": "“日暮寻路”",
        "img": "https://media.prts.wiki/thumb/4/4e/Avatar_activity_AW.png/120px-Avatar_activity_AW.png"
    },
    {
        "name": "“吾导先路”",
        "img": "https://media.prts.wiki/thumb/2/2d/Avatar_activity_GA.png/120px-Avatar_activity_GA.png"
    },
    {
        "name": "“沙洲晨曦”",
        "img": "https://media.prts.wiki/thumb/8/85/Avatar_activity_XB1_1.png/120px-Avatar_activity_XB1_1.png"
    },
    {
        "name": "“搬运任务”",
        "img": "https://media.prts.wiki/thumb/f/f9/Avatar_activity_XB1_2.png/120px-Avatar_activity_XB1_2.png"
    },
    {
        "name": "“一览无余”",
        "img": "https://media.prts.wiki/thumb/2/2c/Avatar_activity_CR.png/120px-Avatar_activity_CR.png"
    },
    {
        "name": "“愚人号”",
        "img": "https://media.prts.wiki/thumb/7/72/Avatar_activity_SN.png/120px-Avatar_activity_SN.png"
    },
    {
        "name": "“隐秘的生命线”",
        "img": "https://media.prts.wiki/thumb/1/10/Avatar_activity_EP14.png/120px-Avatar_activity_EP14.png"
    },
    {
        "name": "“尘影余音”",
        "img": "https://media.prts.wiki/thumb/8/8a/Avatar_activity_LE.png/120px-Avatar_activity_LE.png"
    },
    {
        "name": "“绿野幻梦”",
        "img": "https://media.prts.wiki/thumb/8/8d/Avatar_activity_DV.png/120px-Avatar_activity_DV.png"
    },
    {
        "name": "“春分”",
        "img": "https://media.prts.wiki/thumb/5/58/Avatar_activity_DC.png/120px-Avatar_activity_DC.png"
    },
    {
        "name": "“勇闯天涯”",
        "img": "https://media.prts.wiki/thumb/a/aa/Avatar_activity_RL4_1.png/120px-Avatar_activity_RL4_1.png"
    },
    {
        "name": "“理想城：长夏狂欢季”",
        "img": "https://media.prts.wiki/thumb/2/23/Avatar_activity_IC.png/120px-Avatar_activity_IC.png"
    },
    {
        "name": "“新鲜”",
        "img": "https://media.prts.wiki/thumb/5/57/Avatar_activity_DT.png/120px-Avatar_activity_DT.png"
    },
    {
        "name": "“矢量”",
        "img": "https://media.prts.wiki/thumb/3/3b/Avatar_activity_VEC1.png/120px-Avatar_activity_VEC1.png"
    },
    {
        "name": "“叙拉古人”",
        "img": "https://media.prts.wiki/thumb/d/d7/Avatar_activity_IS.png/120px-Avatar_activity_IS.png"
    },
    {
        "name": "“船舰”",
        "img": "https://media.prts.wiki/thumb/8/8e/Avatar_activity_AC.png/120px-Avatar_activity_AC.png"
    },
    {
        "name": "“登临意”",
        "img": "https://media.prts.wiki/thumb/7/70/Avatar_activity_WB.png/120px-Avatar_activity_WB.png"
    },
    {
        "name": "“追寻”",
        "img": "https://media.prts.wiki/thumb/f/fd/Avatar_activity_RL4_2.png/120px-Avatar_activity_RL4_2.png"
    },
    {
        "name": "“眠于树影之中”",
        "img": "https://media.prts.wiki/thumb/b/b9/Avatar_activity_FD.png/120px-Avatar_activity_FD.png"
    },
    {
        "name": "“照我以火”",
        "img": "https://media.prts.wiki/thumb/1/12/Avatar_activity_FC.png/120px-Avatar_activity_FC.png"
    },
    {
        "name": "“通关”",
        "img": "https://media.prts.wiki/thumb/3/36/Avatar_activity_ARC1.png/120px-Avatar_activity_ARC1.png"
    },
    {
        "name": "“王冠”",
        "img": "https://media.prts.wiki/thumb/f/ff/Avatar_activity_RL4_3.png/120px-Avatar_activity_RL4_3.png"
    }
]

export const AvatarList = mergeUnique(_AvatarList, dataMap.AvatarList, 'name')